# Generated by Django 3.0.5 on 2020-04-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.CharField(default='board', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='bot_hand',
            field=models.CharField(default='bot_hand', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='bot_stack',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='numWins',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player_hand',
            field=models.CharField(default='hand', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='player_name',
            field=models.CharField(default='player_name', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='player_stack',
            field=models.BigIntegerField(default=0),
        ),
    ]
