# Generated by Django 3.0.5 on 2020-04-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200430_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.BigIntegerField(default=0)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='pot',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='core.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='core.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='player_name', max_length=100)),
                ('cards', models.ManyToManyField(to='core.Card')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='bot_hand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bot', to='core.Hand'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_hand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to='core.Hand'),
        ),
    ]
