# Generated by Django 3.0.5 on 2020-05-01 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200430_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='board', to='core.Board'),
        ),
    ]
