# Generated by Django 3.0.5 on 2020-05-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200501_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bot_bet',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player_bet',
            field=models.BigIntegerField(default=0),
        ),
    ]
